using CassaComuneAnM.Core.Enums;

namespace CassaComuneAnM.MauiAppUi.Services;

public sealed record CurrencyOption(CurrencyCode Code, string ItalianName)
{
    public string Label => $"{Code} · {ItalianName.ToUpperInvariant()}";
}

public static class CurrencyCatalog
{
    private static readonly IReadOnlyDictionary<CurrencyCode, string> ItalianNames = new Dictionary<CurrencyCode, string>
    {
        [CurrencyCode.AED] = "dirham degli Emirati Arabi Uniti",
        [CurrencyCode.AFN] = "afghani",
        [CurrencyCode.ALL] = "lek albanese",
        [CurrencyCode.AMD] = "dram armeno",
        [CurrencyCode.ANG] = "fiorino delle Antille olandesi",
        [CurrencyCode.AOA] = "kwanza angolano",
        [CurrencyCode.ARS] = "peso argentino",
        [CurrencyCode.AUD] = "dollaro australiano",
        [CurrencyCode.AWG] = "fiorino di Aruba",
        [CurrencyCode.AZN] = "manat azero",
        [CurrencyCode.BAM] = "marco convertibile della Bosnia-Herzegovina",
        [CurrencyCode.BBD] = "dollaro di Barbados",
        [CurrencyCode.BDT] = "taka bangladese",
        [CurrencyCode.BGN] = "lev bulgaro",
        [CurrencyCode.BHD] = "dinaro del Bahrein",
        [CurrencyCode.BIF] = "franco del Burundi",
        [CurrencyCode.BMD] = "dollaro delle Bermuda",
        [CurrencyCode.BND] = "dollaro del Brunei",
        [CurrencyCode.BOB] = "boliviano",
        [CurrencyCode.BRL] = "real brasiliano",
        [CurrencyCode.BSD] = "dollaro delle Bahamas",
        [CurrencyCode.BTN] = "ngultrum bhutanese",
        [CurrencyCode.BWP] = "pula del Botswana",
        [CurrencyCode.BYN] = "rublo bielorusso",
        [CurrencyCode.BZD] = "dollaro del Belize",
        [CurrencyCode.CAD] = "dollaro canadese",
        [CurrencyCode.CDF] = "franco congolese",
        [CurrencyCode.CHF] = "franco svizzero",
        [CurrencyCode.CLP] = "peso cileno",
        [CurrencyCode.CNY] = "yuan cinese",
        [CurrencyCode.COP] = "peso colombiano",
        [CurrencyCode.CRC] = "colón costaricano",
        [CurrencyCode.CUP] = "peso cubano",
        [CurrencyCode.CVE] = "escudo capoverdiano",
        [CurrencyCode.CZK] = "corona ceca",
        [CurrencyCode.DJF] = "franco di Gibuti",
        [CurrencyCode.DKK] = "corona danese",
        [CurrencyCode.DOP] = "peso dominicano",
        [CurrencyCode.DZD] = "dinaro algerino",
        [CurrencyCode.EGP] = "sterlina egiziana",
        [CurrencyCode.ERN] = "nakfa eritreo",
        [CurrencyCode.ETB] = "birr etiope",
        [CurrencyCode.EUR] = "euro",
        [CurrencyCode.FJD] = "dollaro delle Figi",
        [CurrencyCode.FKP] = "sterlina delle Falkland",
        [CurrencyCode.GBP] = "sterlina britannica",
        [CurrencyCode.GEL] = "lari georgiano",
        [CurrencyCode.GHS] = "cedi ghanese",
        [CurrencyCode.GIP] = "sterlina di Gibilterra",
        [CurrencyCode.GMD] = "dalasi gambiano",
        [CurrencyCode.GNF] = "franco della Guinea",
        [CurrencyCode.GTQ] = "quetzal guatemalteco",
        [CurrencyCode.GYD] = "dollaro della Guyana",
        [CurrencyCode.HKD] = "dollaro di Hong Kong",
        [CurrencyCode.HNL] = "lempira honduregna",
        [CurrencyCode.HTG] = "gourde haitiano",
        [CurrencyCode.HUF] = "fiorino ungherese",
        [CurrencyCode.IDR] = "rupia indonesiana",
        [CurrencyCode.ILS] = "nuovo siclo israeliano",
        [CurrencyCode.INR] = "rupia indiana",
        [CurrencyCode.IQD] = "dinaro iracheno",
        [CurrencyCode.IRR] = "rial iraniano",
        [CurrencyCode.ISK] = "corona islandese",
        [CurrencyCode.JMD] = "dollaro giamaicano",
        [CurrencyCode.JOD] = "dinaro giordano",
        [CurrencyCode.JPY] = "yen giapponese",
        [CurrencyCode.KES] = "scellino keniota",
        [CurrencyCode.KGS] = "som kirghiso",
        [CurrencyCode.KHR] = "riel cambogiano",
        [CurrencyCode.KMF] = "franco comoriano",
        [CurrencyCode.KPW] = "won nordcoreano",
        [CurrencyCode.KRW] = "won sudcoreano",
        [CurrencyCode.KWD] = "dinaro kuwaitiano",
        [CurrencyCode.KYD] = "dollaro delle Isole Cayman",
        [CurrencyCode.KZT] = "tenge kazako",
        [CurrencyCode.LAK] = "kip laotiano",
        [CurrencyCode.LBP] = "lira libanese",
        [CurrencyCode.LKR] = "rupia di Sri Lanka",
        [CurrencyCode.LRD] = "dollaro liberiano",
        [CurrencyCode.LYD] = "dinaro libico",
        [CurrencyCode.MAD] = "dirham marocchino",
        [CurrencyCode.MDL] = "leu moldavo",
        [CurrencyCode.MGA] = "ariary malgascio",
        [CurrencyCode.MKD] = "dinaro macedone",
        [CurrencyCode.MMK] = "kyat di Myanmar",
        [CurrencyCode.MNT] = "tugrik mongolo",
        [CurrencyCode.MOP] = "pataca di Macao",
        [CurrencyCode.MRU] = "ouguiya della Mauritania",
        [CurrencyCode.MUR] = "rupia mauriziana",
        [CurrencyCode.MVR] = "rufiyaa delle Maldive",
        [CurrencyCode.MWK] = "kwacha malawiano",
        [CurrencyCode.MXN] = "peso messicano",
        [CurrencyCode.MYR] = "ringgit malese",
        [CurrencyCode.MZN] = "metical mozambicano",
        [CurrencyCode.NAD] = "dollaro namibiano",
        [CurrencyCode.NGN] = "naira nigeriana",
        [CurrencyCode.NIO] = "córdoba nicaraguense",
        [CurrencyCode.NOK] = "corona norvegese",
        [CurrencyCode.NPR] = "rupia nepalese",
        [CurrencyCode.NZD] = "dollaro neozelandese",
        [CurrencyCode.OMR] = "rial omanita",
        [CurrencyCode.PAB] = "balboa panamense",
        [CurrencyCode.PEN] = "sol peruviano",
        [CurrencyCode.PGK] = "kina papuana",
        [CurrencyCode.PHP] = "peso filippino",
        [CurrencyCode.PKR] = "rupia pakistana",
        [CurrencyCode.PLN] = "zloty polacco",
        [CurrencyCode.PYG] = "guaraní paraguayano",
        [CurrencyCode.QAR] = "rial qatariano",
        [CurrencyCode.RON] = "leu rumeno",
        [CurrencyCode.RSD] = "dinaro serbo",
        [CurrencyCode.RUB] = "rublo russo",
        [CurrencyCode.RWF] = "franco ruandese",
        [CurrencyCode.SAR] = "riyal saudita",
        [CurrencyCode.SBD] = "dollaro delle Isole Salomone",
        [CurrencyCode.SCR] = "rupia delle Seychelles",
        [CurrencyCode.SDG] = "sterlina sudanese",
        [CurrencyCode.SEK] = "corona svedese",
        [CurrencyCode.SGD] = "dollaro di Singapore",
        [CurrencyCode.SHP] = "sterlina di Sant’Elena",
        [CurrencyCode.SLE] = "leone della Sierra Leone",
        [CurrencyCode.SOS] = "scellino somalo",
        [CurrencyCode.SRD] = "dollaro del Suriname",
        [CurrencyCode.SSP] = "sterlina sud-sudanese",
        [CurrencyCode.STN] = "dobra di Sao Tomé e Príncipe",
        [CurrencyCode.SYP] = "lira siriana",
        [CurrencyCode.SZL] = "lilangeni",
        [CurrencyCode.THB] = "baht thailandese",
        [CurrencyCode.TJS] = "somoni tagiko",
        [CurrencyCode.TMT] = "manat turkmeno",
        [CurrencyCode.TND] = "dinaro tunisino",
        [CurrencyCode.TOP] = "paʻanga tongano",
        [CurrencyCode.TRY] = "lira turca",
        [CurrencyCode.TTD] = "dollaro di Trinidad e Tobago",
        [CurrencyCode.TWD] = "nuovo dollaro taiwanese",
        [CurrencyCode.TZS] = "scellino della Tanzania",
        [CurrencyCode.UAH] = "grivnia ucraina",
        [CurrencyCode.UGX] = "scellino ugandese",
        [CurrencyCode.USD] = "dollaro statunitense",
        [CurrencyCode.UYU] = "peso uruguayano",
        [CurrencyCode.UZS] = "sum uzbeco",
        [CurrencyCode.VES] = "bolívar venezuelano",
        [CurrencyCode.VND] = "dong vietnamita",
        [CurrencyCode.VUV] = "vatu di Vanuatu",
        [CurrencyCode.WST] = "tala samoano",
        [CurrencyCode.XAF] = "franco CFA BEAC",
        [CurrencyCode.XCD] = "dollaro dei Caraibi orientali",
        [CurrencyCode.XDR] = "diritti speciali di incasso",
        [CurrencyCode.XOF] = "franco CFA BCEAO",
        [CurrencyCode.XPF] = "franco CFP",
        [CurrencyCode.YER] = "riyal yemenita",
        [CurrencyCode.ZAR] = "rand sudafricano",
        [CurrencyCode.ZMW] = "kwacha zambiano"
    };

    public static IReadOnlyList<CurrencyOption> All { get; } = Enum
        .GetValues<CurrencyCode>()
        .OrderBy(code => code.ToString())
        .Select(code => new CurrencyOption(code, GetItalianName(code)))
        .ToList();

    public static string GetItalianName(CurrencyCode code) => ItalianNames[code];

    public static string GetDisplayLabel(CurrencyCode code) => $"{code} · {GetItalianName(code).ToUpperInvariant()}";
}
